baseurl = "https://chira.city"
languageCode = "ja"
title = "チラシティ"
disableHugoGeneratorInject = true
hasCJKLanguage = true

[Params]
GoogleAnalytics = "UA-46259108-6"
GoogleCloudStrageBucket = "https://storage.googleapis.com/image.chira.city/"

[Indexes]
target = "targets"

[taxonomies]
category = "categories"
tag = "tags"
target = "targets"
