baseurl = "https://mc.chira.city"
languageCode = "ja"
title = "チラシティまつど（βリリース）"
disableHugoGeneratorInject = true
hasCJKLanguage = true

[Params]
GoogleAnalytics = "UA-158119437-1"
GoogleCloudStrageBucket = "https://image.chira.city/"
#GoogleCloudStrageBucket = "https://storage.googleapis.com/image.chira.city/"

[Indexes]
target = "targets"

[taxonomies]
category = "categories"
tag = "tags"
target = "targets"
